{
 "title": "Fulcrum",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "coin",
    "label": "Coin",
    "query": {
     "query": "label_values(fulcrum_controller_info, coin)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values(fulcrum_controller_info{coin=\"$coin\"}, chain)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(fulcrum_controller_info{coin=\"$coin\", chain=\"$chain\"}, instance)"
    }
   },
   {
    "name": "bitcoind_node",
    "query": {
     "query": "label_values(bitcoin_info{coin=\"$coin\", chain=\"$chain\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fulcrum_subsmgr_active_subs_count{instance=\"$node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "fulcrum_subsmgr_unique_subs_count{instance=\"$node\"}",
     "legendFormat": "Unique"
    },
    {
     "expr": "fulcrum_subsmgr_pending_notif_count{instance=\"$node\"}",
     "legendFormat": "Pending notifications"
    },
    {
     "expr": "fulcrum_server_manager_client_count{instance=\"$node\"}",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fulcrum_server_manager_client_count{instance=\"$node\"}",
     "legendFormat": "Total client count"
    },
    {
     "expr": "fulcrum_server_manager_client_count_max_lifetime{instance=\"$node\"}",
     "legendFormat": "Lifetime max client count"
    },
    {
     "expr": "fulcrum_server_manager_server_client_count{instance=\"$node\"}",
     "legendFormat": "Client count {{servertype}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fulcrum_server_manager_peer_count{instance=\"$node\"}",
     "legendFormat": "{{peertype}} count"
    }
   ]
  },
  {
   "title": "Job Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fulcrum_job_queue_extant_jobs{instance=\"$node\"}",
     "legendFormat": "Count"
    },
    {
     "expr": "fulcrum_job_queue_extant_jobs_max_lifetime{instance=\"$node\"}",
     "legendFormat": "Max Count"
    },
    {
     "expr": "fulcrum_job_queue_extant_jobs_limit{instance=\"$node\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "rate(fulcrum_job_queue_count_lifetime{instance=\"$node\"}[5m])",
     "legendFormat": "Job rate"
    },
    {
     "expr": "rate(fulcrum_job_queue_overflows_lifetime{instance=\"$node\"}[5m])",
     "legendFormat": "Overflow rate"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fulcrum_controller_header_count{instance=\"$node\"}",
     "legendFormat": "Header count"
    },
    {
     "expr": "fulcrum_controller_tx_num{instance=\"$node\"}",
     "legendFormat": "TX count"
    }
   ]
  },
  {
   "title": "UTXO Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fulcrum_controller_utxo_set_count{instance=\"$node\"}",
     "legendFormat": "Count"
    },
    {
     "expr": "fulcrum_controller_utxo_set_size_mb{instance=\"$node\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Jemalloc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fulcrum_jemalloc_stats_active{instance=\"$node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "fulcrum_jemalloc_stats_allocated{instance=\"$node\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "fulcrum_jemalloc_stats_mapped{instance=\"$node\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "fulcrum_jemalloc_stats_metadata{instance=\"$node\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "fulcrum_jemalloc_stats_resident{instance=\"$node\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "fulcrum_jemalloc_stats_retained{instance=\"$node\"}",
     "legendFormat": "Retained"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "fulcrum_memory_usage_physical_kb{instance=\"$node\"}",
     "legendFormat": "Physical"
    },
    {
     "expr": "fulcrum_memory_usage_virtual_kb{instance=\"$node\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "RocksDB All Memory Tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fulcrum_storage_db_stats_cur_size_all_mem_tables_bytes{instance=\"$node\"}",
     "legendFormat": "{{database}} size"
    }
   ]
  },
  {
   "title": "RocksDB Table Readers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fulcrum_storage_db_stats_estimate_table_readers_mem_bytes{instance=\"$node\"}",
     "legendFormat": "{{database}} size"
    }
   ]
  },
  {
   "title": "Merkle Header Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fulcrum_storage_caches_merkleheaders{instance=\"$node\",type=\"bytes\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "fulcrum_storage_caches_merkleheaders{instance=\"$node\",type=\"count\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Merge Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fulcrum_storage_merge_calls{instance=\"$node\"}[5m])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Bitcoind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fulcrum_bitcoind_extant_request_contexts{instance=\"$node\"}",
     "legendFormat": "Extant requests"
    },
    {
     "expr": "rate(fulcrum_bitcoind_request_timeout_count{instance=\"$node\"}[1m])",
     "legendFormat": "Timeout rate"
    },
    {
     "expr": "rate(fulcrum_bitcoind_request_zombie_count{instance=\"$node\"}[1m])",
     "legendFormat": "Zombie rate"
    }
   ]
  },
  {
   "title": "TX sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(fulcrum_server_manager_transactions_sent_count{instance=\"$node\"}[1m])",
     "legendFormat": "Count"
    },
    {
     "expr": "rate(fulcrum_server_manager_transactions_sent_size_bytes{instance=\"$node\"}[1m])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fulcrum_controller_header_count{instance=\"$node\"}-1",
     "legendFormat": "Fulcrum height"
    },
    {
     "expr": "bitcoin_blocks{instance=\"$bitcoind_node\"}",
     "legendFormat": "Bitcoind height"
    }
   ]
  }
 ]
}